# This is a basic workflow to help you get started with Actions

name: Node Continuous Integration

on:
  push:
  pull_request:
    branches: 
      - develop


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - cd gcode
      - run: npm ci
      - run: npm test
      - run: npm run build
